# Generated by Django 4.2.14 on 2024-07-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "платеж", "verbose_name_plural": "платежи"},
        ),
    ]
